openapi: 3.0.0
info:
  title: "Todo List"
  description: "A simple to-do list to keep track of your tasks"
  version: "1.0"
servers:
  - url: "/"
    description: "Homepage"
paths:
  /:
    get:
      operationId: get_todo_list
      summary: "Get Todo List"
      description: "Get the list of tasks to be done"
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Todo"
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /add:
    post:
      operationId: add_task
      summary: "Add Task"
      description: "Add a new task to your to-do list to keep track"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoRequest'
      responses:
        '201':
          description: "Task added successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - tasks
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        task:
          type: string
        completed:
          type: boolean
      required:
        - id
        - task
        - completed
    TodoRequest:
      type: object
      properties:
        task:
          type: string
      required:
        - task
    Error:
      type: object
      properties:
        message:
          type: string
